# Generated by Django 3.2.3 on 2021-06-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='location',
            new_name='time_depature',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='url',
        ),
    ]
