# Generated by Django 3.2.3 on 2021-06-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20210605_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='time_depature',
            new_name='address',
        ),
    ]
