# Generated by Django 3.2.3 on 2021-06-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'object', 'verbose_name_plural': 'Objects'},
        ),
    ]
